### ISSUE TITLE
[Bug] Smooth reduces height

### ISSUE THREAD

**Issue by ziplock9000** [Roland09/PathPaintTool#2]
As you can see it's reduced the height where I used the brush that was *only* set to smooth.
So it's taking average values from something that is not the terrain

Screenshot
https://i.imgur.com/3ggNQAR.jpg

**Comment by Roland09** [comment]
Which Unity version are you using? It works fine for me in 2018. However in 2019 Unity seems to have introduced a smooth direction in their shader, which is awesome, and this isn't supported yet and causes the effect you describe in 2019. I like that new setting, I'll add it.

Can you please confirm that Unity's Smooth tool works fine?

**Comment by ziplock9000** [comment]
2019.2.x I still have the same issues. I noticed none of the actual source files have changed when I copied them down, which is reflected on the "last edited 2 months ago"

**Comment by Roland09** [comment]
Thank you. The underlying shader got changed in 2019.2 by Unity. I suspect more changes to come, so I created dedicated branches for 2018.3 and 2019.2. The smoothing should be fixed in this branch:

https://github.com/Roland09/PathPaintTool/tree/unity-2019.2

It also got a smooth direction slider.
