### ISSUE TITLE
[Bug] Height needs much larger multiplier

### ISSUE THREAD

**Issue by ziplock9000** [Roland09/PathPaintTool#3]
Even on maximum brush strength of 200, the height hardly changes.

Screenshot
https://i.imgur.com/ghs0sH4.jpg

**Comment by Roland09** [comment]
Which Unity version are you using exactly? I tried several now, including 2019. Looks fine to me using your settings:

![height](https://user-images.githubusercontent.com/10963432/63401613-3e794d00-c3d8-11e9-9b61-bcd4cd8b2981.gif)

Are you using the sample terrain I provided or your own?

And does Unity's built-in Set Height tool work on the same path?

**Comment by Roland09** [comment]
Tested in 2019.2, works fine.
